font_family		MonoLisaDev Nerd Font
bold_font        	auto
italic_font      	auto
bold_italic_font 	auto

confirm_os_window_close 0

foreground         #E6E7E8
background         #000618
background_opacity 0.25
cursor             #E6E7E8

active_tab_foreground     #000618
active_tab_background     #E6E7E8
inactive_tab_foreground   #E6E7E8
inactive_tab_background   #000618

active_border_color   #E6E7E8
inactive_border_color #000618
bell_border_color     #8193A1

color0       	#0A121F
color1		#8193A1
color2		#4A6881
color3		#695C54
color4		#334D66
color5		#182E62
color6		#1B324D
color7		#4D5860
color8		#070C15
color9		#ADC4D7
color10		#638BAC
color11		#8C7B70
color12		#446789
color13		#203E83
color14		#254367
color15		#191D20
